---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart varnish
  systemd:
    name: varnish
    state: restarted

- name: reload varnish
  systemd:
    name: varnish
    state: reloaded